apiVersion: streaming.tanzu.vmware.com/v1alpha1
kind: ClusterStream
metadata:
  name: cluster-stream-kafka-1
spec:
  keys: ["truckclass", "truckid"]
  streamModes: ["read", "write"]
  storage:
    servers:
      - url: "http://localhost:8080"
        protocol: "kafka"
    attributes:
      key1: "value1"
    reclaimPolicy: "Retain"
---
apiVersion: streaming.tanzu.vmware.com/v1alpha1
kind: ClusterStream
metadata:
  name: cluster-stream-rabbitmq-1
spec:
  keys: ["truckclass", "truckid"]
  streamModes: ["read", "write"]
  storage:
    servers:
      - url: "http://localhost:8080"
        protocol: "rabbitmq"
    attributes:
      key1: "value1"
    reclaimPolicy: "Retain"
---
apiVersion: streaming.tanzu.vmware.com/v1alpha1
kind: Stream
metadata:
  name: kafka-stream-1
spec:
  keys: ["album", "genre"]
  streamMode: ["read"]
  protocol: "kafka"
  storage:
    clusterStream: "cluster-stream-kafka-1"
---
apiVersion: streaming.tanzu.vmware.com/v1alpha1
kind: Stream
metadata:
  name: rabbitmq-stream-1
spec:
  keys: ["truckclass", "truckid"]
  streamMode: ["write"]
  protocol: "rabbitmq"
  storage:
    clusterStream: "cluster-stream-rabbitmq-1"
---
apiVersion: streaming.tanzu.vmware.com/v1alpha1
kind: Processor
metadata:
  name: processor1
spec:
  inputs:
    sources:
      - name: "kafka-stream-1"
  outputs:
    - name: "rabbitmq-stream-1"
  template:
    spec:
      containers:
        - name: uppercase-grpc
          image: tzolov/poc-uppercase-grpc:latest
          env:
            - name: SPRING_CLOUD_FUNCTION_DEFINITION
              value: uppercase
            - name: SPRING_CLOUD_FUNCTION_GRPC_MODE
              value: server
            - name: SPRING_CLOUD_FUNCTION_GRPC_PORT
              value: "55554"


