site_name: Streaming Runtime
dev_addr: '0.0.0.0:8000'
theme:
  name: material
  custom_dir: material

  features:
    - navigation.tabs
  logo: assets/icon-tanzu2.svg
  favicon: assets/icon-tanzu2.svg
  palette:
#    primary: blue grey
#    accent: cyan
    - scheme: default
      media: "(prefers-color-scheme: light)"
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
#        primary: blue grey
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

repo_url: https://github.com/vmware-tanzu/streaming-runtimes

#extra_css:
#  - stylesheets/extra.css

markdown_extensions:
  - footnotes
  - tables
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true

# Page tree
nav:
  - Home: index.md
  - Streaming Runtime:
      - Install: install.md
      - Overview: streaming-runtime-overview.md
      - Architecture: 
        - Processors:
          - Overview: architecture/processors/overview.md
          - User Defined Functions:
              - Overview: architecture/processors/udf/overview.md
              - Build your function: architecture/processors/udf/usage.md
          - Spring Cloud Stream: architecture/processors/scs/overview.md
          - FSQL: architecture/processors/fsql/overview.md
        - Cluster Streams:
          - Overview: architecture/cluster-streams/overview.md
        - Streams:
          - Overview: architecture/streams/overview.md
          - Stream Data Schema: architecture/streams/streaming-data-schema.md
        - Service Binding: architecture/service-binding/service-binding.md
      
      - Build: streaming-runtime-build.md
  - Samples:
      - Overview: samples/overview.md
      - How to Run: samples/instructions.md
      - Use Cases:
        - Anomaly Detection: samples/anomaly-detection/anomaly-detection.md
        - Clickstream Analysis: samples/clickstream/clickstream.md
        - IoT Monitoring: samples/iot-monitoring/iot-monitoring.md
        - Music Chart: samples/top-k-songs/top-k-songs.md
        - SCS TickTock: samples/spring-cloud-stream/tick-tock.md

copyright: "Copyright © 2022 The Tanzu Streaming Runtime Authors"

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/vmware-tanzu/streaming-runtimes
      name: Streaming Runtime Community on Github
    - icon: fontawesome/brands/slack
      link: https://kubernetes.slack.com/archives/C03GFRBHM43
      name: Slack
