site_name: Streaming Runtime

theme:
  name: material
  custom_dir: material

  features:
    - navigation.tabs
  logo: assets/icon-tanzu.svg
  favicon: assets/icon-tanzu.svg
  palette:
#    primary: blue grey
#    accent: cyan
    - scheme: default
      media: "(prefers-color-scheme: light)"
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
#        primary: blue grey
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

repo_url: https://github.com/vmware-tanzu/streaming-runtimes

#extra_css:
#  - stylesheets/extra.css

markdown_extensions:
  - tables
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true

# Page tree
nav:
  - Home: index.md
  - Streaming Runtime:
      - Install: install.md
      - Usage: streaming-runtime-usage.md
      - Build: streaming-runtime-build.md
#      - Javadoc: 'https://s01.oss.sonatype.org/service/local/repositories/releases/archive/net/datafaker/datafaker/1.1.0/datafaker-1.1.0-javadoc.jar/!/index.html'
      - User Defined Functions:
          - Architecture: udf/architecture.md
          - Usage: udf/usage.md
      - Service Binding: service-binding/service-binding.md
  - Sample Use Cases:
      - Overview: samples/overview.md
      - Instructions: samples/instructions.md
      - Use Cases:
        - Anomaly Detection: samples/anomaly-detection/anomaly-detection.md
        - Clickstream Analysis: samples/clickstream/clickstream.md
        - IoT Monitoring: samples/iot-monitoring/iot-monitoring.md
        - Music Chart: samples/top-k-songs/top-k-songs.md

copyright: "Copyright © 2022 The Tanzu Streaming Runtime Authors"

extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/vmwaretap
    - icon: fontawesome/brands/github
      link: https://github.com/vmware-tanzu/streaming-runtimes
      name: Streaming Runtime Community on Github
    - icon: fontawesome/brands/slack
      link: https://join.slack.com/share/enQtMzE3MTc4MjY3NzM2MS1mZDdmNzQyYTQwNTljZjc0NWY1Y2M4NTRmNThlODA0YmVlMGIwMDUxZmVmYzAzNjFkOTUwMWI2NzMwNzAzY2Q4
      name: Slack