apiVersion: apps/v1
kind: Deployment
metadata:
  name: streaming-runtime-processor
  labels:
    app: streaming-runtime-processor
    component: streaming-runtime-processor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: streaming-runtime-processor
  template:
    metadata:
      labels:
        app: streaming-runtime-processor
        component: streaming-runtime-processor
