name: scw-processor
image: ghcr.io/vmware-tanzu/streaming-runtimes/scw-processor:latest
ports:
  - containerPort: 8080
env:
  - name: SPRING_CLOUD_FUNCTION_GRPC_PORT
    value: "55554"
  - name: SPRING_CLOUD_FUNCTION_GRPC_SERVER
    value: "false"
  - name: SPRING_CLOUD_FUNCTION_DEFINITION
    value: "proxy"
  - name: LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_CLOUD_STREAM_BINDER
    value: "ERROR"
livenessProbe:
  httpGet:
    path: /actuator/health
    port: 8080
  initialDelaySeconds: 10
  periodSeconds: 60
readinessProbe:
  httpGet:
    path: /actuator/info
    port: 8080
  initialDelaySeconds: 10
  periodSeconds: 10