apiVersion: v1
kind: Service
metadata:
  name: streaming-runtime-processor
  labels:
    app: streaming-runtime-processor
spec:
  ports:
  - port: 8080
    name: streaming-runtime-processor
  clusterIP: None
  selector:
    app: streaming-runtime-processor
