name: multibinder-grpc
image: ghcr.io/vmware-tanzu/streaming-runtimes/multibinder-grpc:latest
ports:
  - containerPort: 8080
env:
  - name: SPRING_CLOUD_FUNCTION_GRPC_PORT
    value: "55554"
  - name: SPRING_CLOUD_FUNCTION_GRPC_SERVER
    value: "false"
livenessProbe:
  httpGet:
    path: /actuator/health
    port: 8080
  initialDelaySeconds: 10
  periodSeconds: 60
readinessProbe:
  httpGet:
    path: /actuator/info
    port: 8080
  initialDelaySeconds: 10
  periodSeconds: 10