// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: payload_collection.proto

package com.tanzu.streaming.runtime.processor.common.proto;

public interface GrpcPayloadCollectionOrBuilder extends
    // @@protoc_insertion_point(interface_extends:GrpcPayloadCollection)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated bytes payload = 1;</code>
   * @return A list containing the payload.
   */
  java.util.List<com.google.protobuf.ByteString> getPayloadList();
  /**
   * <code>repeated bytes payload = 1;</code>
   * @return The count of payload.
   */
  int getPayloadCount();
  /**
   * <code>repeated bytes payload = 1;</code>
   * @param index The index of the element to return.
   * @return The payload at the given index.
   */
  com.google.protobuf.ByteString getPayload(int index);
}
