// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: payload_collection.proto

package com.tanzu.streaming.runtime.processor.common.proto;

/**
 * Protobuf type {@code GrpcPayloadCollection}
 */
public final class GrpcPayloadCollection extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:GrpcPayloadCollection)
    GrpcPayloadCollectionOrBuilder {
private static final long serialVersionUID = 0L;
  // Use GrpcPayloadCollection.newBuilder() to construct.
  private GrpcPayloadCollection(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private GrpcPayloadCollection() {
    payload_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new GrpcPayloadCollection();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private GrpcPayloadCollection(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              payload_ = new java.util.ArrayList<com.google.protobuf.ByteString>();
              mutable_bitField0_ |= 0x00000001;
            }
            payload_.add(input.readBytes());
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        payload_ = java.util.Collections.unmodifiableList(payload_); // C
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.tanzu.streaming.runtime.processor.common.proto.PayloadCollection.internal_static_GrpcPayloadCollection_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.tanzu.streaming.runtime.processor.common.proto.PayloadCollection.internal_static_GrpcPayloadCollection_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.tanzu.streaming.runtime.processor.common.proto.GrpcPayloadCollection.class, com.tanzu.streaming.runtime.processor.common.proto.GrpcPayloadCollection.Builder.class);
  }

  public static final int PAYLOAD_FIELD_NUMBER = 1;
  private java.util.List<com.google.protobuf.ByteString> payload_;
  /**
   * <code>repeated bytes payload = 1;</code>
   * @return A list containing the payload.
   */
  @java.lang.Override
  public java.util.List<com.google.protobuf.ByteString>
      getPayloadList() {
    return payload_;
  }
  /**
   * <code>repeated bytes payload = 1;</code>
   * @return The count of payload.
   */
  public int getPayloadCount() {
    return payload_.size();
  }
  /**
   * <code>repeated bytes payload = 1;</code>
   * @param index The index of the element to return.
   * @return The payload at the given index.
   */
  public com.google.protobuf.ByteString getPayload(int index) {
    return payload_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < payload_.size(); i++) {
      output.writeBytes(1, payload_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    {
      int dataSize = 0;
      for (int i = 0; i < payload_.size(); i++) {
        dataSize += com.google.protobuf.CodedOutputStream
          .computeBytesSizeNoTag(payload_.get(i));
      }
      size += dataSize;
      size += 1 * getPayloadList().size();
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.tanzu.streaming.runtime.processor.common.proto.GrpcPayloadCollection)) {
      return super.equals(obj);
    }
    com.tanzu.streaming.runtime.processor.common.proto.GrpcPayloadCollection other = (com.tanzu.streaming.runtime.processor.common.proto.GrpcPayloadCollection) obj;

    if (!getPayloadList()
        .equals(other.getPayloadList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getPayloadCount() > 0) {
      hash = (37 * hash) + PAYLOAD_FIELD_NUMBER;
      hash = (53 * hash) + getPayloadList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.tanzu.streaming.runtime.processor.common.proto.GrpcPayloadCollection parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.tanzu.streaming.runtime.processor.common.proto.GrpcPayloadCollection parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.tanzu.streaming.runtime.processor.common.proto.GrpcPayloadCollection parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.tanzu.streaming.runtime.processor.common.proto.GrpcPayloadCollection parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.tanzu.streaming.runtime.processor.common.proto.GrpcPayloadCollection parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.tanzu.streaming.runtime.processor.common.proto.GrpcPayloadCollection parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.tanzu.streaming.runtime.processor.common.proto.GrpcPayloadCollection parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.tanzu.streaming.runtime.processor.common.proto.GrpcPayloadCollection parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.tanzu.streaming.runtime.processor.common.proto.GrpcPayloadCollection parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.tanzu.streaming.runtime.processor.common.proto.GrpcPayloadCollection parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.tanzu.streaming.runtime.processor.common.proto.GrpcPayloadCollection parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.tanzu.streaming.runtime.processor.common.proto.GrpcPayloadCollection parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.tanzu.streaming.runtime.processor.common.proto.GrpcPayloadCollection prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code GrpcPayloadCollection}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:GrpcPayloadCollection)
      com.tanzu.streaming.runtime.processor.common.proto.GrpcPayloadCollectionOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.tanzu.streaming.runtime.processor.common.proto.PayloadCollection.internal_static_GrpcPayloadCollection_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.tanzu.streaming.runtime.processor.common.proto.PayloadCollection.internal_static_GrpcPayloadCollection_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.tanzu.streaming.runtime.processor.common.proto.GrpcPayloadCollection.class, com.tanzu.streaming.runtime.processor.common.proto.GrpcPayloadCollection.Builder.class);
    }

    // Construct using com.tanzu.streaming.runtime.processor.common.proto.GrpcPayloadCollection.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      payload_ = java.util.Collections.emptyList();
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.tanzu.streaming.runtime.processor.common.proto.PayloadCollection.internal_static_GrpcPayloadCollection_descriptor;
    }

    @java.lang.Override
    public com.tanzu.streaming.runtime.processor.common.proto.GrpcPayloadCollection getDefaultInstanceForType() {
      return com.tanzu.streaming.runtime.processor.common.proto.GrpcPayloadCollection.getDefaultInstance();
    }

    @java.lang.Override
    public com.tanzu.streaming.runtime.processor.common.proto.GrpcPayloadCollection build() {
      com.tanzu.streaming.runtime.processor.common.proto.GrpcPayloadCollection result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.tanzu.streaming.runtime.processor.common.proto.GrpcPayloadCollection buildPartial() {
      com.tanzu.streaming.runtime.processor.common.proto.GrpcPayloadCollection result = new com.tanzu.streaming.runtime.processor.common.proto.GrpcPayloadCollection(this);
      int from_bitField0_ = bitField0_;
      if (((bitField0_ & 0x00000001) != 0)) {
        payload_ = java.util.Collections.unmodifiableList(payload_);
        bitField0_ = (bitField0_ & ~0x00000001);
      }
      result.payload_ = payload_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.tanzu.streaming.runtime.processor.common.proto.GrpcPayloadCollection) {
        return mergeFrom((com.tanzu.streaming.runtime.processor.common.proto.GrpcPayloadCollection)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.tanzu.streaming.runtime.processor.common.proto.GrpcPayloadCollection other) {
      if (other == com.tanzu.streaming.runtime.processor.common.proto.GrpcPayloadCollection.getDefaultInstance()) return this;
      if (!other.payload_.isEmpty()) {
        if (payload_.isEmpty()) {
          payload_ = other.payload_;
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          ensurePayloadIsMutable();
          payload_.addAll(other.payload_);
        }
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.tanzu.streaming.runtime.processor.common.proto.GrpcPayloadCollection parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.tanzu.streaming.runtime.processor.common.proto.GrpcPayloadCollection) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<com.google.protobuf.ByteString> payload_ = java.util.Collections.emptyList();
    private void ensurePayloadIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        payload_ = new java.util.ArrayList<com.google.protobuf.ByteString>(payload_);
        bitField0_ |= 0x00000001;
       }
    }
    /**
     * <code>repeated bytes payload = 1;</code>
     * @return A list containing the payload.
     */
    public java.util.List<com.google.protobuf.ByteString>
        getPayloadList() {
      return ((bitField0_ & 0x00000001) != 0) ?
               java.util.Collections.unmodifiableList(payload_) : payload_;
    }
    /**
     * <code>repeated bytes payload = 1;</code>
     * @return The count of payload.
     */
    public int getPayloadCount() {
      return payload_.size();
    }
    /**
     * <code>repeated bytes payload = 1;</code>
     * @param index The index of the element to return.
     * @return The payload at the given index.
     */
    public com.google.protobuf.ByteString getPayload(int index) {
      return payload_.get(index);
    }
    /**
     * <code>repeated bytes payload = 1;</code>
     * @param index The index to set the value at.
     * @param value The payload to set.
     * @return This builder for chaining.
     */
    public Builder setPayload(
        int index, com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensurePayloadIsMutable();
      payload_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated bytes payload = 1;</code>
     * @param value The payload to add.
     * @return This builder for chaining.
     */
    public Builder addPayload(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensurePayloadIsMutable();
      payload_.add(value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated bytes payload = 1;</code>
     * @param values The payload to add.
     * @return This builder for chaining.
     */
    public Builder addAllPayload(
        java.lang.Iterable<? extends com.google.protobuf.ByteString> values) {
      ensurePayloadIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, payload_);
      onChanged();
      return this;
    }
    /**
     * <code>repeated bytes payload = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearPayload() {
      payload_ = java.util.Collections.emptyList();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:GrpcPayloadCollection)
  }

  // @@protoc_insertion_point(class_scope:GrpcPayloadCollection)
  private static final com.tanzu.streaming.runtime.processor.common.proto.GrpcPayloadCollection DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.tanzu.streaming.runtime.processor.common.proto.GrpcPayloadCollection();
  }

  public static com.tanzu.streaming.runtime.processor.common.proto.GrpcPayloadCollection getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<GrpcPayloadCollection>
      PARSER = new com.google.protobuf.AbstractParser<GrpcPayloadCollection>() {
    @java.lang.Override
    public GrpcPayloadCollection parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new GrpcPayloadCollection(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<GrpcPayloadCollection> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<GrpcPayloadCollection> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.tanzu.streaming.runtime.processor.common.proto.GrpcPayloadCollection getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

