// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: payload_collection.proto

package com.tanzu.streaming.runtime.processor.common.proto;

public final class PayloadCollection {
  private PayloadCollection() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GrpcPayloadCollection_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GrpcPayloadCollection_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\030payload_collection.proto\"(\n\025GrpcPayloa" +
      "dCollection\022\017\n\007payload\030\001 \003(\014B6\n2com.tanz" +
      "u.streaming.runtime.processor.common.pro" +
      "toP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_GrpcPayloadCollection_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_GrpcPayloadCollection_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GrpcPayloadCollection_descriptor,
        new java.lang.String[] { "Payload", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
