apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: streaming-runtime-cluster-role
rules:
  - apiGroups:
      - streaming.tanzu.vmware.com
    resources:
      - clusterstreams
      - streams
      - processors
    verbs:
      - get
      - list
      - watch
      - patch
      - create
  - apiGroups:
      - streaming.tanzu.vmware.com
    resources:
      - clusterstreams/status
      - streams/status
      - processors/status
    verbs:
      - patch
      - get
      - list
      - watch
  - apiGroups:
      - "events.k8s.io"
    resources:
      - events
    verbs:
      - create
  - apiGroups:
      - ""
    resources:
      - services
      - pods
      - configmaps
      - secrets
    verbs:
      - get
      - list
      - watch
      - patch
      - create
  - apiGroups:
      - apps
    resources:
      - deployments
    verbs:
      - get
      - list
      - create
      - patch
      - watch
  - apiGroups:
      - rabbitmq.com
    resources:
      - rabbitmqclusters
      - queues
      - exchanges
      - bindings
    verbs:
      - get
      - list
      - watch
      - patch
      - create