apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: clusterstreams.streaming.tanzu.vmware.com
spec:
  group: streaming.tanzu.vmware.com
  versions:
    - name: v1alpha1
      served: true
      storage: true
      subresources:
        status: { }
      additionalPrinterColumns:
        - jsonPath: .status.conditions[?(@.type=="Ready")].status
          name: Ready
          type: string
        - jsonPath: .status.conditions[?(@.type=="Ready")].reason
          name: Reason
          type: string
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                name:
                  type: string
                keys:
                  type: array
                  items:
                    type: string
                streamModes:
                  type: array
                  items:
                    type: string
                storage:
                  type: object
                  properties:
                    server:
                      type: object
                      properties:
                        url:
                          type: string
                        protocol:
                          type: string
                        binding:
                          type: string
                    attributes:
                      type: object
                      additionalProperties:
                        type: string
                    reclaimPolicy:
                      type: string
              required: [ "name" ]              
            status:
              type: object
              properties:
                binding:
                  type: object
                  properties:
                    name:
                      type: string
                conditions:
                  type: array
                  items:
                    type: object
                    properties:
                      type:
                        type: string
                        description: The unique identifier of a condition, used to distinguish between other conditions in the resource.
                      status:
                        type: string
                        description: The status of the condition, either True, False or Unknown.
                      lastTransitionTime:
                        type: string
                        description: Last time the condition of a type changed from one status to another. The required format is 'yyyy-MM-ddTHH:mm:ssZ', in the UTC time zone.
                      reason:
                        type: string
                        description: The reason for the condition's last transition (a single word in CamelCase).
                  description: List of status conditions.
                storageAddress:
                  type: object
                  properties:
                    server:
                      type: object
                      additionalProperties:
                        type: object
                        properties:
                          url:
                            type: string
                          protocol:
                            type: string
                          protocolVersion:
                            type: string
                          description:
                            type: string
                          variables:
                            type: object
                            additionalProperties:
                              type: string
  scope: Cluster
  names:
    plural: clusterstreams
    singular: clusterstream
    kind: ClusterStream
    shortNames:
      - srcs
