apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: processors.streaming.tanzu.vmware.com
spec:
  group: streaming.tanzu.vmware.com
  versions:
    - name: v1alpha1
      served: true
      storage: true
      subresources:
        status: { }
      additionalPrinterColumns:
        - jsonPath: .status.conditions[?(@.type=="Ready")].status
          name: Ready
          type: string
        - jsonPath: .status.conditions[?(@.type=="Ready")].reason
          name: Reason
          type: string
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                inputs:
                  type: object
                  properties:
                    query:
                      type: array
                      items:
                        type: string
                    debug:
                      type: object
                      properties:
                        query:
                          type: string
                        explain:
                          type: array
                          items:
                            type: integer
                    sources:
                      type: array
                      items:
                        type: object
                        properties:
                          name:
                            type: string
                outputs:
                  type: array
                  items:
                    type: object
                    properties:
                      name:
                        type: string
                template:
                  type: object
                  properties:
                    spec:
                      type: object
                      properties:
                        containers:
                          type: array
                          items:
                            type: object
                            properties:
                              name:
                                type: string
                              image:
                                type: string
                              env:
                                type: array
                                items:
                                  type: object
                                  properties:
                                    name:
                                      type: string
                                    value:
                                      type: string
            status:
              type: object
              properties:
                conditions:
                  type: array
                  items:
                    type: object
                    properties:
                      type:
                        type: string
                        description: The unique identifier of a condition, used to distinguish between other conditions in the resource.
                      status:
                        type: string
                        description: The status of the condition, either True, False or Unknown.
                      lastTransitionTime:
                        type: string
                        description: Last time the condition of a type changed from one status to another. The required format is 'yyyy-MM-ddTHH:mm:ssZ', in the UTC time zone.
                      reason:
                        type: string
                        description: The reason for the condition's last transition (a single word in CamelCase).
                  description: List of status conditions.
  scope: Namespaced
  names:
    plural: processors
    singular: processor
    kind: Processor
    shortNames:
      - srp
