apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: streams.streaming.tanzu.vmware.com
spec:
  group: streaming.tanzu.vmware.com
  versions:
    - name: v1alpha1
      served: true
      storage: true
      subresources:
        status: { }
      additionalPrinterColumns:
        - jsonPath: .status.conditions[?(@.type=="Ready")].status
          name: Ready
          type: string
        - jsonPath: .status.conditions[?(@.type=="Ready")].reason
          name: Reason
          type: string
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                keys:
                  type: array
                  items:
                    type: string
                protocol:
                  type: string
                streamMode:
                  type: array
                  items:
                    type: string
                storage:
                  type: object
                  properties:
                    clusterStream:
                      type: string
                attributes:
                  type: object
                  additionalProperties:
                    type: string
                dataSchemaContext:
                  type: object
                  properties:
                    inline:
                      type: object
                      properties:
                        type:
                          type: string
                        schema:
                          type: string
                      required: [ "type", "schema" ]
                    schema:
                      type: object
                      properties:
                        name:
                          type: string
                        namespace:
                          type: string
                        fields:
                          type: array
                          items:
                            type: object
                            properties:
                              name:
                                type: string
                              type:
                                type: string
                              logicalType:
                                type: string
                              optional:
                                type: boolean
                              watermark:
                                type: string
                              metadata:
                                type: object
                                properties:
                                  from:
                                    type: string
                                  readonly:
                                    type: boolean
                                required: [ "from" ]
                            required: [ "name", "type" ]
                      required: [ "name", "namespace", "fields" ]
                    metadataFields:
                      type: array
                      items:
                        type: object
                        properties:
                          name:
                            type: string
                          type:
                            type: string
                          logicalType:
                            type: string
                          optional:
                            type: boolean
                          watermark:
                            type: string
                          metadata:
                            type: object
                            properties:
                              from:
                                type: string
                              readonly:
                                type: boolean
                            required: [ "from" ]
                        required: [ "name", "type" ]
                    primaryKey:
                      type: array
                      items:
                        type: string
                    timeAttributes:
                      type: array
                      items:
                        type: object
                        properties:
                          name:
                            type: string
                          watermark:
                            type: string
                        required: [ "name" ]
                    options:
                      type: object
                      additionalProperties:
                        type: string
                  oneOf:
                    - properties:
                      required: [ "inline" ]
                    - properties:
                      required: [ "schema" ]
            status:
              type: object
              properties:
                conditions:
                  type: array
                  items:
                    type: object
                    properties:
                      type:
                        type: string
                        description: The unique identifier of a condition, used to distinguish between other conditions in the resource.
                      status:
                        type: string
                        description: The status of the condition, either True, False or Unknown.
                      lastTransitionTime:
                        type: string
                        description: Last time the condition of a type changed from one status to another. The required format is 'yyyy-MM-ddTHH:mm:ssZ', in the UTC time zone.
                      reason:
                        type: string
                        description: The reason for the condition's last transition (a single word in CamelCase).
                  description: List of status conditions.
                storageAddress:
                  type: object
                  properties:
                    servers:
                      type: object
                      additionalProperties:
                        type: object
                        properties:
                          url:
                            type: string
                          protocol:
                            type: string
                          protocolVersion:
                            type: string
                          description:
                            type: string
                          variables:
                            type: object
                            additionalProperties:
                              type: string
  scope: Namespaced
  names:
    plural: streams
    singular: stream
    kind: Stream
    shortNames:
      - srs
