/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.tanzu.streaming.runtime.playsongs.avro;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class PlayEvent extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 8995962009218989710L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"PlayEvent\",\"namespace\":\"com.tanzu.streaming.runtime.playsongs.avro\",\"fields\":[{\"name\":\"song_id\",\"type\":\"long\"},{\"name\":\"duration\",\"type\":\"long\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<PlayEvent> ENCODER =
      new BinaryMessageEncoder<PlayEvent>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<PlayEvent> DECODER =
      new BinaryMessageDecoder<PlayEvent>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<PlayEvent> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<PlayEvent> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<PlayEvent> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<PlayEvent>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this PlayEvent to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a PlayEvent from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a PlayEvent instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static PlayEvent fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

   private long song_id;
   private long duration;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public PlayEvent() {}

  /**
   * All-args constructor.
   * @param song_id The new value for song_id
   * @param duration The new value for duration
   */
  public PlayEvent(java.lang.Long song_id, java.lang.Long duration) {
    this.song_id = song_id;
    this.duration = duration;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return song_id;
    case 1: return duration;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: song_id = (java.lang.Long)value$; break;
    case 1: duration = (java.lang.Long)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'song_id' field.
   * @return The value of the 'song_id' field.
   */
  public long getSongId() {
    return song_id;
  }


  /**
   * Sets the value of the 'song_id' field.
   * @param value the value to set.
   */
  public void setSongId(long value) {
    this.song_id = value;
  }

  /**
   * Gets the value of the 'duration' field.
   * @return The value of the 'duration' field.
   */
  public long getDuration() {
    return duration;
  }


  /**
   * Sets the value of the 'duration' field.
   * @param value the value to set.
   */
  public void setDuration(long value) {
    this.duration = value;
  }

  /**
   * Creates a new PlayEvent RecordBuilder.
   * @return A new PlayEvent RecordBuilder
   */
  public static com.tanzu.streaming.runtime.playsongs.avro.PlayEvent.Builder newBuilder() {
    return new com.tanzu.streaming.runtime.playsongs.avro.PlayEvent.Builder();
  }

  /**
   * Creates a new PlayEvent RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new PlayEvent RecordBuilder
   */
  public static com.tanzu.streaming.runtime.playsongs.avro.PlayEvent.Builder newBuilder(com.tanzu.streaming.runtime.playsongs.avro.PlayEvent.Builder other) {
    if (other == null) {
      return new com.tanzu.streaming.runtime.playsongs.avro.PlayEvent.Builder();
    } else {
      return new com.tanzu.streaming.runtime.playsongs.avro.PlayEvent.Builder(other);
    }
  }

  /**
   * Creates a new PlayEvent RecordBuilder by copying an existing PlayEvent instance.
   * @param other The existing instance to copy.
   * @return A new PlayEvent RecordBuilder
   */
  public static com.tanzu.streaming.runtime.playsongs.avro.PlayEvent.Builder newBuilder(com.tanzu.streaming.runtime.playsongs.avro.PlayEvent other) {
    if (other == null) {
      return new com.tanzu.streaming.runtime.playsongs.avro.PlayEvent.Builder();
    } else {
      return new com.tanzu.streaming.runtime.playsongs.avro.PlayEvent.Builder(other);
    }
  }

  /**
   * RecordBuilder for PlayEvent instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<PlayEvent>
    implements org.apache.avro.data.RecordBuilder<PlayEvent> {

    private long song_id;
    private long duration;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.tanzu.streaming.runtime.playsongs.avro.PlayEvent.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.song_id)) {
        this.song_id = data().deepCopy(fields()[0].schema(), other.song_id);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.duration)) {
        this.duration = data().deepCopy(fields()[1].schema(), other.duration);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
    }

    /**
     * Creates a Builder by copying an existing PlayEvent instance
     * @param other The existing instance to copy.
     */
    private Builder(com.tanzu.streaming.runtime.playsongs.avro.PlayEvent other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.song_id)) {
        this.song_id = data().deepCopy(fields()[0].schema(), other.song_id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.duration)) {
        this.duration = data().deepCopy(fields()[1].schema(), other.duration);
        fieldSetFlags()[1] = true;
      }
    }

    /**
      * Gets the value of the 'song_id' field.
      * @return The value.
      */
    public long getSongId() {
      return song_id;
    }


    /**
      * Sets the value of the 'song_id' field.
      * @param value The value of 'song_id'.
      * @return This builder.
      */
    public com.tanzu.streaming.runtime.playsongs.avro.PlayEvent.Builder setSongId(long value) {
      validate(fields()[0], value);
      this.song_id = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'song_id' field has been set.
      * @return True if the 'song_id' field has been set, false otherwise.
      */
    public boolean hasSongId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'song_id' field.
      * @return This builder.
      */
    public com.tanzu.streaming.runtime.playsongs.avro.PlayEvent.Builder clearSongId() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'duration' field.
      * @return The value.
      */
    public long getDuration() {
      return duration;
    }


    /**
      * Sets the value of the 'duration' field.
      * @param value The value of 'duration'.
      * @return This builder.
      */
    public com.tanzu.streaming.runtime.playsongs.avro.PlayEvent.Builder setDuration(long value) {
      validate(fields()[1], value);
      this.duration = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'duration' field has been set.
      * @return True if the 'duration' field has been set, false otherwise.
      */
    public boolean hasDuration() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'duration' field.
      * @return This builder.
      */
    public com.tanzu.streaming.runtime.playsongs.avro.PlayEvent.Builder clearDuration() {
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public PlayEvent build() {
      try {
        PlayEvent record = new PlayEvent();
        record.song_id = fieldSetFlags()[0] ? this.song_id : (java.lang.Long) defaultValue(fields()[0]);
        record.duration = fieldSetFlags()[1] ? this.duration : (java.lang.Long) defaultValue(fields()[1]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<PlayEvent>
    WRITER$ = (org.apache.avro.io.DatumWriter<PlayEvent>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<PlayEvent>
    READER$ = (org.apache.avro.io.DatumReader<PlayEvent>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeLong(this.song_id);

    out.writeLong(this.duration);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.song_id = in.readLong();

      this.duration = in.readLong();

    } else {
      for (int i = 0; i < 2; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.song_id = in.readLong();
          break;

        case 1:
          this.duration = in.readLong();
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










