# 1. Message Retransmission
apiVersion: streaming.tanzu.vmware.com/v1alpha1
kind: Processor
metadata:
  name: re-transmission-processor
spec:
  type: SRP
  inputs:
    - name: data-in
  outputs:
    - name: data-out
