# 3. Inline (e.g. in SRP Processor) Data Transformation 
apiVersion: streaming.tanzu.vmware.com/v1alpha1
kind: Processor
metadata:
  name: inline-transformation
spec:
  type: SRP
  inputs:
    - name: data-in
  outputs:
    - name: data-out
  attributes:
    srp.output.headers: "user=payload.fullName"  
    srp.spel.expression: '''{"'' + #jsonPath(payload, ''$.fullName'') + ''":"'' + #jsonPath(payload, ''$.email'') + ''"}'''
