# 3.1 Polyglot UDF Transformation
apiVersion: streaming.tanzu.vmware.com/v1alpha1
kind: Processor
metadata:
  name: udf-transformation
spec:
  type: SRP
  inputs:
    - name: data-in
  outputs:
    - name: data-out
  attributes:
   srp.grpcPort: "50051"
  template:
    spec:
      containers:
        - name: uppercase-grpc-python
          # Runs GRPC server on port 50051
          image: ghcr.io/vmware-tanzu/streaming-runtimes/udf-uppercase-python:0.1
