# 4. Stateless Replication
apiVersion: streaming.tanzu.vmware.com/v1alpha1
kind: Processor
metadata:
  name: stateless-replication
spec:
  # 3 instances
  replicas: 3
  inputs:
    - name: data-in
  outputs:
    - name: data-out
  # attributes:
  #   forceStatefulSet: "true"