# 5.1 Partition by Field using Header Keys
apiVersion: streaming.tanzu.vmware.com/v1alpha1
kind: Processor
metadata:
  name: user-partition-processor
spec:
  type: SRP
  inputs:
    - name: data-in
  outputs:
    - name: partitioned-by-team-stream
  attributes:
    # The header name used for partitioning must match the outbound stream's spec.keys names!!!
    srp.output.headers: "team=payload.team"
---
apiVersion: streaming.tanzu.vmware.com/v1alpha1
kind: Stream
metadata:
  name: partitioned-by-team-stream
spec:
  name: partitioned-by-team
  protocol: kafka
  # The 'team' is expected to be a inbound message header name!!!
  keys: ["team"]
  partitionCount: 3
---
apiVersion: streaming.tanzu.vmware.com/v1alpha1
kind: Processor
metadata:
  name: user-scores-processor
spec:
  type: SRP
  replicas: 3
  inputs:
    - name: partitioned-by-team-stream
  outputs:
    - name: team-scores
  attributes:
    srp.spel.expression: "'Team:' + #jsonPath(payload, '$.team') + ', Score:' + #jsonPath(payload, '$.score')"
