#
#
apiVersion: streaming.tanzu.vmware.com/v1alpha1
kind: Stream
metadata:
  name: data-in-stream
spec:
  name: data-in
  protocol: "kafka"
---
apiVersion: streaming.tanzu.vmware.com/v1alpha1
kind: Processor
metadata:
  name: multibinder-processor
spec:
  inputs:
    - name: data-in-stream
  outputs:
    - name: data-out-stream
---
apiVersion: streaming.tanzu.vmware.com/v1alpha1
kind: Stream
metadata:
  name: data-out-stream
spec:
  name: data-out
  protocol: "rabbitmq"
  # Binding refs a Secret with same name. The stream controller uses this binding to configure ClusterStream's auto-creation
  binding: "data-out-stream-cluster-stream-default-user"

  attributes:
    # Prerequisites to provision RabbitMQ clusters with the the "rabbitmq-operator":
    # https://vmware-tanzu.github.io/streaming-runtimes/install/#optional-install-rabbitmq-cluster-and-message-topology-operators
    protocolAdapterName: "rabbitmq-operator"
---
apiVersion: servicebinding.io/v1beta1
kind: ServiceBinding
metadata:
  name: streaming-runtime-rabbitmq
spec:
  service:
    apiVersion: v1
    kind: Secret
    name: data-out-stream-cluster-stream-default-user
  workload:
    apiVersion: apps/v1
    kind: Deployment
    name: multibinder-processor
  env:
    - name: SPRING_RABBITMQ_PASSWORD
      key: password
    - name: SPRING_RABBITMQ_USERNAME
      key: username
    - name: RABBITMQ_HOST
      key: host
    - name: RABBITMQ_PORT
      key: port
