#
# We can use the RabbitMQ Cluster Operator to provision our RabbitMQ Cluster and the ServiceBinding Operator to share the RabbitMQ 
# credentials with the processors that would need to connect to it.
#
# Prerequisites:
# - Service Binding Operator: https://vmware-tanzu.github.io/streaming-runtimes/install/#optional-install-service-binding-operator
# - RabbitMQ Cluster and Message Topology Operators: https://vmware-tanzu.github.io/streaming-runtimes/install/#optional-install-rabbitmq-cluster-and-message-topology-operators
apiVersion: streaming.tanzu.vmware.com/v1alpha1
kind: Stream
metadata:
  name: data-in-stream
spec:
  name: data-in
  protocol: "kafka"
---
apiVersion: streaming.tanzu.vmware.com/v1alpha1
kind: Processor
metadata:
  name: multibinder-processor
spec:
  inputs:
    - name: data-in-stream
  outputs:
    - name: data-out-stream
---
apiVersion: streaming.tanzu.vmware.com/v1alpha1
kind: Stream
metadata:
  name: data-out-stream
spec:
  name: data-out
  protocol: "rabbitmq"
  # Binding refs a Secret with same name. The stream controller uses this binding to configure ClusterStream's auto-creation
  binding: "data-out-stream-cluster-stream-default-user"

  attributes:
    # Prerequisites to provision RabbitMQ clusters with the the "rabbitmq-operator":
    # https://vmware-tanzu.github.io/streaming-runtimes/install/#optional-install-rabbitmq-cluster-and-message-topology-operators
    protocolAdapterName: "rabbitmq-operator"
---
apiVersion: servicebinding.io/v1beta1
kind: ServiceBinding
metadata:
  name: streaming-runtime-rabbitmq
spec:
  service:
    apiVersion: v1
    kind: Secret
    # This is the secret generated by the RabbitMQ Cluster operator. Convention is:
    # '<cluster-stream-name>-default-user'
    # When the ClusterStream is automatically generated from the Stream Operator, the name convention is:
    # '<stream-name>-cluster-stream-default-user'
    name: data-out-stream-cluster-stream-default-user
  workload:
    apiVersion: apps/v1
    kind: Deployment
    # Currently, the convention expects that the workload name is: 'srp-<your-processor-name>'.
    # TODO: Explore generating the ServiceBindings resources in the  StreamingRuntime Operator.
    name: srp-multibinder-processor
  env:
    # As we know that this processor uses Spring RabbitMQ configuration, here we pass in the expected conf.
    - name: SPRING_RABBITMQ_PASSWORD
      key: password
    - name: SPRING_RABBITMQ_USERNAME
      key: username
