apiVersion: streaming.tanzu.vmware.com/v1alpha1
kind: Stream
metadata:
  name: iot-monitoring-stream
spec:
  name: iot-monitoring
  protocol: "kafka"
  storage:
    clusterStream: "iot-monitoring-cluster-stream"
  streamMode: [ "read" ]
  keys: [ "error_code" ]
  dataSchemaContext:
    schema:
      namespace: com.tanzu.streaming.runtime.iot.log
      name: MonitoringStream
      fields:
        - name: error_code
          type: string
        - name: type
          type: string
        - name: application
          type: string
        - name: version
          type: string
        - name: description
          type: string
        - name: ts
          type: long_timestamp-millis
          watermark: "`ts` - INTERVAL '3' SECONDS"
    options:
      ddl.scan.startup.mode: earliest-offset
---
apiVersion: streaming.tanzu.vmware.com/v1alpha1
kind: Stream
metadata:
  name: error-count-stream
spec:
  name: error-count
  protocol: "kafka"
  storage:
    clusterStream: "error-count-cluster-stream"
  streamMode: [ "read", "write" ]
  keys: [ "error_code" ]
  dataSchemaContext:
    schema:
      namespace: com.tanzu.streaming.runtime.iot.log
      name: ErrorCount
      fields:
        - name: window_start
          type: long_timestamp-millis
        - name: window_end
          type: long_timestamp-millis
        - name: error_code
          type: string
        - name: error_count
          type: long
    options:
      ddl.key.fields: error_code
      ddl.value.format: "json"
      ddl.properties.allow.auto.create.topics: "true"
      ddl.scan.startup.mode: earliest-offset
---
apiVersion: streaming.tanzu.vmware.com/v1alpha1
kind: Stream
metadata:
  name: udf-output-error-count-stream
spec:
  name: udf-output-error-count
  keys: [ "error_code" ]
  streamMode: [ "write" ]
  protocol: "rabbitmq"
  storage:
    clusterStream: "udf-output-error-count-cluster-stream"
---
apiVersion: streaming.tanzu.vmware.com/v1alpha1
kind: Processor
metadata:
  name: iot-monitoring-sql-aggregation
spec:
  type: FSQL
  inlineQuery:
    - "INSERT INTO [[STREAM:error-count-stream]] 
        SELECT window_start, window_end, error_code, COUNT(*) AS error_count 
        FROM TABLE(TUMBLE(TABLE [[STREAM:iot-monitoring-stream]], DESCRIPTOR(ts), INTERVAL '1' MINUTE)) 
        WHERE type='ERROR' 
        GROUP BY window_start, window_end, error_code"
  attributes:
    debugQuery: "SELECT * FROM ErrorCount"
    debugExplain: "2"
---
apiVersion: streaming.tanzu.vmware.com/v1alpha1
kind: Processor
metadata:
  name: iot-monitoring-udf
spec:
  type: TWA
  inputs:
    - name: "error-count-stream"
  outputs:
    - name: "udf-output-error-count-stream"
  template:
    spec:
      containers:
        - name: iot-monitoring-error-code-udf
          image: ghcr.io/vmware-tanzu/streaming-runtimes/udf-uppercase-go:0.1

