apiVersion: v1
kind: Service
metadata:
  name: top-k-songs-data-generator
  labels:
    app: top-k-songs-data-generator
    component: top-k-songs-data-generator
    type: streaming-spike
    spring-deployment-id: top-k-songs-data-generator
spec:
  type: LoadBalancer
  ports:
    - port: 80
      name: top-k-songs-data-generator
      targetPort: 8080
      protocol: TCP

  selector:
    app: top-k-songs-data-generator
    component: top-k-songs-data-generator
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: top-k-songs-data-generator
  labels:
    app: top-k-songs-data-generator
    type: streaming-spike
    component: top-k-songs-data-generator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: top-k-songs-data-generator
  template:
    metadata:
      labels:
        app: top-k-songs-data-generator
        component: top-k-songs-data-generator
    spec:
      terminationGracePeriodSeconds: 15
      containers:
        - name: top-k-songs-data-generator
          image: ghcr.io/vmware-tanzu/streaming-runtimes/stream-data-generator:latest
          ports:
            - containerPort: 8080
          env:
            - name: MY_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: STREAM_DATA_GENERATOR_KAFKASERVER
              value: kafka.$(MY_NAMESPACE).svc.cluster.local:9092
            - name: STREAM_DATA_GENERATOR_SCHEMAREGISTRYSERVER
              value: http://s-registry.$(MY_NAMESPACE).svc.cluster.local:8081
            - name: STREAM_DATA_GENERATOR_TERMINATEAFTER
              value: '200h'

            - name: STREAM_DATA_GENERATOR_STREAMS_0_STREAMNAME
              value: 'kafka-stream-songs'
            - name: STREAM_DATA_GENERATOR_STREAMS_0_AVROSCHEMA
              value: |-
                {
                 "namespace": "com.tanzu.streaming.runtime.playsongs.avro",
                 "type": "record",
                 "name": "Song",
                 "doc": "unique_on=song_id;to_share=song_id",
                 "fields": [
                     {"name": "song_id", "type": "long",   "doc" : "#{number.number_between '1','1000'}"},
                     {"name": "album",   "type": "string", "doc" : "#{ancient.hero} #{ancient.god}"},
                     {"name": "artist",  "type": "string", "doc" : "#{artist.names}"},
                     {"name": "name",    "type": "string", "doc" : "#{rock_band.name}"},
                     {"name": "genre",   "type": "string", "doc" : "#{music.genres}"}
                 ]
                }
            - name: STREAM_DATA_GENERATOR_STREAMS_0_VALUEFORMAT
              value: 'AVRO_SCHEMA_REGISTRY'
            - name: STREAM_DATA_GENERATOR_STREAMS_0_BATCH_SIZE
              value: '100'
            - name: STREAM_DATA_GENERATOR_STREAMS_0_BATCH_INITIALDELAY
              value: '1ms'
            - name: STREAM_DATA_GENERATOR_STREAMS_0_BATCH_MESSAGEDELAY
              value: '10ms'

            - name: STREAM_DATA_GENERATOR_STREAMS_1_STREAMNAME
              value: 'kafka-stream-playevents'
            - name: STREAM_DATA_GENERATOR_STREAMS_1_AVROSCHEMA
              value: |-
                {
                 "namespace": "com.tanzu.streaming.runtime.playsongs.avro",
                 "type": "record",
                 "name": "PlayEvent",
                 "fields": [
                   {"name": "song_id",  "type": "long", "doc":"[[#shared.field('song.song_id')?:9999]]" },
                   {"name": "duration", "type": "long", "doc":"#{number.number_between '30000','1000000'}" }
                 ]
                }
            - name: STREAM_DATA_GENERATOR_STREAMS_1_VALUEFORMAT
              value: 'AVRO_SCHEMA_REGISTRY'
            - name: STREAM_DATA_GENERATOR_STREAMS_1_BATCH_SIZE
              value: '1'
            - name: STREAM_DATA_GENERATOR_STREAMS_1_BATCH_INITIALDELAY
              value: '10ms'
            - name: STREAM_DATA_GENERATOR_STREAMS_1_BATCH_DELAY
              value: '100ms'
            - name: STREAM_DATA_GENERATOR_STREAMS_1_BATCH_MESSAGEDELAY
              value: '100ms'
