# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: MessageService.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='MessageService.proto',
  package='org.springframework.cloud.function.grpc',
  syntax='proto3',
  serialized_options=b'P\001',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x14MessageService.proto\x12\'org.springframework.cloud.function.grpc\"\xa2\x01\n\x0bGrpcMessage\x12\x0f\n\x07payload\x18\x01 \x01(\x0c\x12R\n\x07headers\x18\x02 \x03(\x0b\x32\x41.org.springframework.cloud.function.grpc.GrpcMessage.HeadersEntry\x1a.\n\x0cHeadersEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x32\x86\x04\n\x10MessagingService\x12z\n\x08\x62iStream\x12\x34.org.springframework.cloud.function.grpc.GrpcMessage\x1a\x34.org.springframework.cloud.function.grpc.GrpcMessage(\x01\x30\x01\x12|\n\x0c\x63lientStream\x12\x34.org.springframework.cloud.function.grpc.GrpcMessage\x1a\x34.org.springframework.cloud.function.grpc.GrpcMessage(\x01\x12|\n\x0cserverStream\x12\x34.org.springframework.cloud.function.grpc.GrpcMessage\x1a\x34.org.springframework.cloud.function.grpc.GrpcMessage0\x01\x12z\n\x0crequestReply\x12\x34.org.springframework.cloud.function.grpc.GrpcMessage\x1a\x34.org.springframework.cloud.function.grpc.GrpcMessageB\x02P\x01\x62\x06proto3'
)




_GRPCMESSAGE_HEADERSENTRY = _descriptor.Descriptor(
  name='HeadersEntry',
  full_name='org.springframework.cloud.function.grpc.GrpcMessage.HeadersEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='org.springframework.cloud.function.grpc.GrpcMessage.HeadersEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='org.springframework.cloud.function.grpc.GrpcMessage.HeadersEntry.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'8\001',
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=182,
  serialized_end=228,
)

_GRPCMESSAGE = _descriptor.Descriptor(
  name='GrpcMessage',
  full_name='org.springframework.cloud.function.grpc.GrpcMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='payload', full_name='org.springframework.cloud.function.grpc.GrpcMessage.payload', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='headers', full_name='org.springframework.cloud.function.grpc.GrpcMessage.headers', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_GRPCMESSAGE_HEADERSENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=66,
  serialized_end=228,
)

_GRPCMESSAGE_HEADERSENTRY.containing_type = _GRPCMESSAGE
_GRPCMESSAGE.fields_by_name['headers'].message_type = _GRPCMESSAGE_HEADERSENTRY
DESCRIPTOR.message_types_by_name['GrpcMessage'] = _GRPCMESSAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GrpcMessage = _reflection.GeneratedProtocolMessageType('GrpcMessage', (_message.Message,), {

  'HeadersEntry' : _reflection.GeneratedProtocolMessageType('HeadersEntry', (_message.Message,), {
    'DESCRIPTOR' : _GRPCMESSAGE_HEADERSENTRY,
    '__module__' : 'MessageService_pb2'
    # @@protoc_insertion_point(class_scope:org.springframework.cloud.function.grpc.GrpcMessage.HeadersEntry)
    })
  ,
  'DESCRIPTOR' : _GRPCMESSAGE,
  '__module__' : 'MessageService_pb2'
  # @@protoc_insertion_point(class_scope:org.springframework.cloud.function.grpc.GrpcMessage)
  })
_sym_db.RegisterMessage(GrpcMessage)
_sym_db.RegisterMessage(GrpcMessage.HeadersEntry)


DESCRIPTOR._options = None
_GRPCMESSAGE_HEADERSENTRY._options = None

_MESSAGINGSERVICE = _descriptor.ServiceDescriptor(
  name='MessagingService',
  full_name='org.springframework.cloud.function.grpc.MessagingService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=231,
  serialized_end=749,
  methods=[
  _descriptor.MethodDescriptor(
    name='biStream',
    full_name='org.springframework.cloud.function.grpc.MessagingService.biStream',
    index=0,
    containing_service=None,
    input_type=_GRPCMESSAGE,
    output_type=_GRPCMESSAGE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='clientStream',
    full_name='org.springframework.cloud.function.grpc.MessagingService.clientStream',
    index=1,
    containing_service=None,
    input_type=_GRPCMESSAGE,
    output_type=_GRPCMESSAGE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='serverStream',
    full_name='org.springframework.cloud.function.grpc.MessagingService.serverStream',
    index=2,
    containing_service=None,
    input_type=_GRPCMESSAGE,
    output_type=_GRPCMESSAGE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='requestReply',
    full_name='org.springframework.cloud.function.grpc.MessagingService.requestReply',
    index=3,
    containing_service=None,
    input_type=_GRPCMESSAGE,
    output_type=_GRPCMESSAGE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_MESSAGINGSERVICE)

DESCRIPTOR.services_by_name['MessagingService'] = _MESSAGINGSERVICE

# @@protoc_insertion_point(module_scope)
