apiVersion: v1
kind: Service
metadata:
  name: kafka-kowl-ui
  labels:
    app: kafka-kowl-ui
spec:
  type: LoadBalancer
  ports:
    - port: 80
      name: kafka-kowl-ui
      targetPort: 8080
      protocol: TCP

  selector:
    app: kafka-kowl-ui
    component: kafka-kowl-ui
