apiVersion: v1
kind: Service
metadata:
  name: clickstream-data-generator
  labels:
    app: clickstream-data-generator
    component: clickstream-data-generator
    type: streaming-spike
    spring-deployment-id: clickstream-data-generator
spec:
  type: LoadBalancer
  ports:
    - port: 80
      name: clickstream-data-generator
      targetPort: 8080
      protocol: TCP

  selector:
    app: clickstream-data-generator
    component: clickstream-data-generator
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: clickstream-data-generator
  labels:
    app: clickstream-data-generator
    type: streaming-spike
    component: clickstream-data-generator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: clickstream-data-generator
  template:
    metadata:
      labels:
        app: clickstream-data-generator
        component: clickstream-data-generator
    spec:
      terminationGracePeriodSeconds: 15
      containers:
        - name: clickstream-data-generator
          image: ghcr.io/vmware-tanzu/streaming-runtimes/kafka-data-generator:latest
          ports:
            - containerPort: 8080
          env:
            - name: MY_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: KAFKA_DATA_GENERATOR_KAFKASERVER
              value: kafka.$(MY_NAMESPACE).svc.cluster.local:9092
            - name: KAFKA_DATA_GENERATOR_SCHEMAREGISTRYSERVER
              value: http://s-registry.$(MY_NAMESPACE).svc.cluster.local:8081
            - name: KAFKA_DATA_GENERATOR_TERMINATEAFTER
              value: '200h'
            - name: KAFKA_DATA_GENERATOR_SHAREDFIELDNAMES
              value: 'user_id'
            - name: KAFKA_DATA_GENERATOR_TOPICS_0_TOPICNAME
              value: 'kafka-stream-user'
            - name: KAFKA_DATA_GENERATOR_TOPICS_0_AVROSCHEMA
              value: |-
                {
                  "namespace": "com.tanzu.streaming.runtime.clickstream.etl",
                  "type": "record",
                  "name": "User",
                  "fields": [
                    {
                      "name": "user_id",
                      "type": "string",
                      "doc": "#{id_number.valid}"
                    },
                    {
                      "name": "name",
                      "type": "string",
                      "doc": "#{name.fullName}"
                    },
                    {
                      "name": "level",
                      "type": "string",
                      "doc": "#{options.option 'BRONZE','SILVER','GOLD','PLATINUM'}"
                    }
                  ]
                }
            - name: KAFKA_DATA_GENERATOR_TOPICS_0_VALUEFORMAT
              value: 'AVRO'
            - name: KAFKA_DATA_GENERATOR_TOPICS_0_SHAREDFIELDSMODE
              value: 'PRODUCER'
            - name: KAFKA_DATA_GENERATOR_TOPICS_0_BATCH_SIZE
              value: '100'
            - name: KAFKA_DATA_GENERATOR_TOPICS_0_BATCH_INITIALDELAY
              value: '10ms'
            - name: KAFKA_DATA_GENERATOR_TOPICS_0_BATCH_MESSAGEDELAY
              value: '100ms'
            - name: KAFKA_DATA_GENERATOR_TOPICS_1_TOPICNAME
              value: 'kafka-stream-click'
            - name: KAFKA_DATA_GENERATOR_TOPICS_1_AVROSCHEMA
              value: |-
                namespace: com.tanzu.streaming.runtime.clickstream.etl
                type: record
                name: Click
                fields:
                  - name: user_id
                    type: string
                    doc: "#{id_number.valid}"
                  - name: page
                    type: int
                    doc: "#{number.number_between '1','100000'}"
                  - name: action
                    type: string
                    doc: "#{options.option 'vitrine_nav','checkout','product_detail','products','selection','cart'}"
                  - name: device
                    type: string
                    doc: "#{options.option 'mobile','computer','tablet'}"
                  - name: agent
                    type: string
                    doc: "#{internet.userAgentAny}"
            - name: KAFKA_DATA_GENERATOR_TOPICS_1_VALUEFORMAT
              value: 'AVRO'
            - name: KAFKA_DATA_GENERATOR_TOPICS_1_SHAREDFIELDSMODE
              value: 'CONSUMER'
            - name: KAFKA_DATA_GENERATOR_TOPICS_1_BATCH_SIZE
              value: '1'
            - name: KAFKA_DATA_GENERATOR_TOPICS_1_BATCH_INITIALDELAY
              value: '100ms'
            - name: KAFKA_DATA_GENERATOR_TOPICS_1_BATCH_DELAY
              value: '500ms'
            - name: KAFKA_DATA_GENERATOR_TOPICS_1_BATCH_MESSAGEDELAY
              value: '100ms'
